package net.cassiolandim.dxf.legacy

import net.cassiolandim.dxf.lldxf.DXFTag
import net.cassiolandim.dxf.lldxf.Types

class HeaderVars {

    def static singleValue = { def value, int code = 1 ->
        return Types.castTag(new DXFTag(code, value))
    }

    def static point2D = { def value ->
        return new DXFTag(10, [value[0], value[1]])
    }

    def static point3D = { def value ->
        return new DXFTag(10, [value[0], value[1], value[2]])
    }

    def static final VARMAP = [
        '$ACADVER': singleValue.rcurry(1),
        '$ANGBASE': singleValue.rcurry(50),
        '$ANGDIR': singleValue.rcurry(70),
        '$ATTDIA': singleValue.rcurry(70),
        '$ATTMODE': singleValue.rcurry(70),
        '$ATTREQ': singleValue.rcurry(70),
        '$AUNITS': singleValue.rcurry(70),
        '$AUPREC': singleValue.rcurry(70),
        '$BLIPMODE': singleValue.rcurry(70),
        '$CECOLOR': singleValue.rcurry(62),
        '$CELTYPE': singleValue.rcurry(6),
        '$CHAMFERA': singleValue.rcurry(40),
        '$CHAMFERB': singleValue.rcurry(40),
        '$CLAYER': singleValue.rcurry(8),
        '$COORDS': singleValue.rcurry(70),
        '$DIMALT': singleValue.rcurry(70),
        '$DIMALTD': singleValue.rcurry(70),
        '$DIMALTF': singleValue.rcurry(40),
        '$DIMAPOST': singleValue.rcurry(1),
        '$DIMASO': singleValue.rcurry(70),
        '$DIMASZ': singleValue.rcurry(40),
        '$DIMBLK': singleValue.rcurry(1),
        '$DIMBLK1': singleValue.rcurry(1),
        '$DIMBLK2': singleValue.rcurry(1),
        '$DIMCEN': singleValue.rcurry(40),
        '$DIMCLRD': singleValue.rcurry(70),
        '$DIMCLRE': singleValue.rcurry(70),
        '$DIMCLRT': singleValue.rcurry(70),
        '$DIMDLE': singleValue.rcurry(40),
        '$DIMDLI': singleValue.rcurry(40),
        '$DIMEXE': singleValue.rcurry(40),
        '$DIMEXO': singleValue.rcurry(40),
        '$DIMGAP': singleValue.rcurry(40),
        '$DIMLFAC': singleValue.rcurry(40),
        '$DIMLIM': singleValue.rcurry(70),
        '$DIMPOST': singleValue.rcurry(1),
        '$DIMRND': singleValue.rcurry(40),
        '$DIMSAH': singleValue.rcurry(70),
        '$DIMSCALE': singleValue.rcurry(40),
        '$DIMSE1': singleValue.rcurry(70),
        '$DIMSE2': singleValue.rcurry(70),
        '$DIMSHO': singleValue.rcurry(70),
        '$DIMSOXD': singleValue.rcurry(70),
        '$DIMSTYLE': singleValue.rcurry(2),
        '$DIMTAD': singleValue.rcurry(70),
        '$DIMTFAC': singleValue.rcurry(40),
        '$DIMTIH': singleValue.rcurry(70),
        '$DIMTIX': singleValue.rcurry(70),
        '$DIMTM': singleValue.rcurry(40),
        '$DIMTOFL': singleValue.rcurry(70),
        '$DIMTOH': singleValue.rcurry(70),
        '$DIMTOL': singleValue.rcurry(70),
        '$DIMTP': singleValue.rcurry(40),
        '$DIMTSZ': singleValue.rcurry(40),
        '$DIMTVP': singleValue.rcurry(40),
        '$DIMTXT': singleValue.rcurry(40),
        '$DIMZIN': singleValue.rcurry(70),
        '$DWGCODEPAGE': singleValue.rcurry(3),
        '$DRAGMODE': singleValue.rcurry(70),
        '$ELEVATION': singleValue.rcurry(40),
        '$EXTMAX': point3D,
        '$EXTMIN': point3D,
        '$FILLETRAD': singleValue.rcurry(40),
        '$FILLMODE': singleValue.rcurry(70),
        '$HANDLING': singleValue.rcurry(70),
        '$HANDSEED': singleValue.rcurry(5),
        '$INSBASE': point3D,
        '$LIMCHECK': singleValue.rcurry(70),
        '$LIMMAX': point2D,
        '$LIMMIN': point2D,
        '$LTSCALE': singleValue.rcurry(40),
        '$LUNITS': singleValue.rcurry(70),
        '$LUPREC': singleValue.rcurry(70),
        '$MAXACTVP': singleValue.rcurry(70),
        '$MENU': singleValue.rcurry(1),
        '$MIRRTEXT': singleValue.rcurry(70),
        '$ORTHOMODE': singleValue.rcurry(70),
        '$OSMODE': singleValue.rcurry(70),
        '$PDMODE': singleValue.rcurry(70),
        '$PDSIZE': singleValue.rcurry(40),
        '$PELEVATION': singleValue.rcurry(40),
        '$PEXTMAX': point3D,
        '$PEXTMIN': point3D,
        '$PLIMCHECK': singleValue.rcurry(70),
        '$PLIMMAX': point2D,
        '$PLIMMIN': point2D,
        '$PLINEGEN': singleValue.rcurry(70),
        '$PLINEWID': singleValue.rcurry(40),
        '$PSLTSCALE': singleValue.rcurry(70),
        '$PUCSNAME': singleValue.rcurry(2),
        '$PUCSORG': point3D,
        '$PUCSXDIR': point3D,
        '$PUCSYDIR': point3D,
        '$QTEXTMODE': singleValue.rcurry(70),
        '$REGENMODE': singleValue.rcurry(70),
        '$SHADEDGE': singleValue.rcurry(70),
        '$SHADEDIF': singleValue.rcurry(70),
        '$SKETCHINC': singleValue.rcurry(40),
        '$SKPOLY': singleValue.rcurry(70),
        '$SPLFRAME': singleValue.rcurry(70),
        '$SPLINESEGS': singleValue.rcurry(70),
        '$SPLINETYPE': singleValue.rcurry(70),
        '$SURFTAB1': singleValue.rcurry(70),
        '$SURFTAB2': singleValue.rcurry(70),
        '$SURFTYPE': singleValue.rcurry(70),
        '$SURFU': singleValue.rcurry(70),
        '$SURFV': singleValue.rcurry(70),
        '$TDCREATE': singleValue.rcurry(40),
        '$TDINDWG': singleValue.rcurry(40),
        '$TDUPDATE': singleValue.rcurry(40),
        '$TDUSRTIMER': singleValue.rcurry(40),
        '$TEXTSIZE': singleValue.rcurry(40),
        '$TEXTSTYLE': singleValue.rcurry(7),
        '$THICKNESS': singleValue.rcurry(40),
        '$TILEMODE': singleValue.rcurry(70),
        '$TRACEWID': singleValue.rcurry(40),
        '$UCSNAME': singleValue.rcurry(2),
        '$UCSORG': point3D,
        '$UCSXDIR': point3D,
        '$UCSYDIR': point3D,
        '$UNITMODE': singleValue.rcurry(70),
        '$USERI1': singleValue.rcurry(70),
        '$USERI2': singleValue.rcurry(70),
        '$USERI3': singleValue.rcurry(70),
        '$USERI4': singleValue.rcurry(70),
        '$USERI5': singleValue.rcurry(70),
        '$USERR1': singleValue.rcurry(40),
        '$USERR2': singleValue.rcurry(40),
        '$USERR3': singleValue.rcurry(40),
        '$USERR4': singleValue.rcurry(40),
        '$USERR5': singleValue.rcurry(40),
        '$USRTIMER': singleValue.rcurry(70),
        '$VISRETAIN': singleValue.rcurry(70),
        '$WORLDVIEW': singleValue.rcurry(70)
    ]
}
